// Checksum vectors in this file were computed independently with a
// throwaway Python script (RFC 1071 algorithm over the IPv4 pseudo-header
// + TCP segment) and hardcoded here -- never generated by calling
// Wirestack's own tcp.cpp code.

#include "wirestack/tcp.hpp"

#include "test_util.hpp"

using wirestack::Ipv4Address;
using wirestack::parseTcpOptions;
using wirestack::parseTcpSegment;
using wirestack::serializeTcpSegment;
using wirestack::TcpOptionParseError;
using wirestack::TcpParseError;
using wirestack::TcpParsedOptions;
using wirestack::TcpSegment;
using wirestack::TcpSerializeError;

namespace {

std::vector<std::byte> toBytes(std::initializer_list<std::uint8_t> values) {
    std::vector<std::byte> out;
    out.reserve(values.size());
    for (auto v : values) {
        out.push_back(static_cast<std::byte>(v));
    }
    return out;
}

std::vector<std::byte> toBytes(std::string_view text) {
    std::vector<std::byte> out;
    out.reserve(text.size());
    for (char c : text) {
        out.push_back(static_cast<std::byte>(static_cast<unsigned char>(c)));
    }
    return out;
}

Ipv4Address ipA() {
    return *Ipv4Address::parse("10.0.0.1");
}
Ipv4Address ipB() {
    return *Ipv4Address::parse("10.0.0.2");
}

// Vector 1: SYN, no options, no payload. src=10.0.0.1 dst=10.0.0.2,
// srcport=54321 dstport=8080 seq=1000 ack=0 flags=SYN window=65535.
// Checksum 0xa436, independently computed.
std::vector<std::byte> vector1Bytes() {
    return toBytes({
        0xd4, 0x31,             // source port 54321
        0x1f, 0x90,             // destination port 8080
        0x00, 0x00, 0x03, 0xe8, // sequence number 1000
        0x00, 0x00, 0x00, 0x00, // acknowledgment number 0
        0x50, 0x02,             // data offset 5, flags SYN
        0xff, 0xff,             // window 65535
        0xa4, 0x36,             // checksum
        0x00, 0x00,             // urgent pointer
    });
}

// Vector 2: SYN|ACK with a 4-byte options area (data offset 6, 24-byte
// header). src=10.0.0.2 dst=10.0.0.1 srcport=8080 dstport=54321 seq=5000
// ack=1001 flags=SYN|ACK window=14600 options={02 04 05 b4}.
// Checksum 0x3fd9, independently computed.
std::vector<std::byte> vector2Bytes() {
    return toBytes({
        0x1f, 0x90,             // source port 8080
        0xd4, 0x31,             // destination port 54321
        0x00, 0x00, 0x13, 0x88, // sequence number 5000
        0x00, 0x00, 0x03, 0xe9, // acknowledgment number 1001
        0x60, 0x12,             // data offset 6, flags SYN|ACK
        0x39, 0x08,             // window 14600
        0x3f, 0xd9,             // checksum
        0x00, 0x00,             // urgent pointer
        0x02, 0x04, 0x05, 0xb4, // options (opaque to Wirestack)
    });
}

// Vector 3: PSH|ACK with a 5-byte payload (odd total length: 25 bytes).
// src=10.0.0.2 dst=10.0.0.1 srcport=11111 dstport=22222 seq=42 ack=43
// flags=PSH|ACK window=4096 payload="hello". Checksum 0xc568,
// independently computed.
std::vector<std::byte> vector3Bytes() {
    return toBytes({
        0x2b, 0x67,             // source port 11111
        0x56, 0xce,             // destination port 22222
        0x00, 0x00, 0x00, 0x2a, // sequence number 42
        0x00, 0x00, 0x00, 0x2b, // acknowledgment number 43
        0x50, 0x18,             // data offset 5, flags PSH|ACK
        0x10, 0x00,             // window 4096
        0xc5, 0x68,             // checksum
        0x00, 0x00,             // urgent pointer
        0x68, 0x65, 0x6c, 0x6c, 0x6f, // "hello"
    });
}

} // namespace

int main() {
    // known-vector parse: base 20-byte SYN
    {
        auto result = parseTcpSegment(vector1Bytes(), ipA(), ipB());
        CHECK(std::holds_alternative<TcpSegment>(result));
        if (auto* segment = std::get_if<TcpSegment>(&result)) {
            CHECK(segment->source_port == 54321);
            CHECK(segment->destination_port == 8080);
            CHECK(segment->sequence_number == 1000);
            CHECK(segment->acknowledgment_number == 0);
            CHECK(segment->flags.syn);
            CHECK(!segment->flags.ack);
            CHECK(segment->window_size == 65535);
            CHECK(segment->options.empty());
            CHECK(segment->payload.empty());
        }
    }

    // known-vector parse: options present, data offset 6 -- proves Data
    // Offset is honored, not assumed to be 20 bytes.
    {
        auto result = parseTcpSegment(vector2Bytes(), ipB(), ipA());
        CHECK(std::holds_alternative<TcpSegment>(result));
        if (auto* segment = std::get_if<TcpSegment>(&result)) {
            CHECK(segment->source_port == 8080);
            CHECK(segment->destination_port == 54321);
            CHECK(segment->sequence_number == 5000);
            CHECK(segment->acknowledgment_number == 1001);
            CHECK(segment->flags.syn);
            CHECK(segment->flags.ack);
            CHECK(segment->options == toBytes({0x02, 0x04, 0x05, 0xb4}));
            CHECK(segment->payload.empty());
        }
    }

    // known-vector parse: odd total length, payload slicing with a
    // 5-byte payload -- second independent checksum vector.
    {
        auto result = parseTcpSegment(vector3Bytes(), ipB(), ipA());
        CHECK(std::holds_alternative<TcpSegment>(result));
        if (auto* segment = std::get_if<TcpSegment>(&result)) {
            CHECK(segment->flags.psh);
            CHECK(segment->flags.ack);
            CHECK(!segment->flags.syn);
            CHECK(segment->payload == toBytes("hello"));
        }
    }

    // known-vector serialize, exact byte comparison against vector 3 --
    // proves serialization independently, not just parsing, for this
    // odd-length vector.
    {
        TcpSegment segment;
        segment.source_port = 11111;
        segment.destination_port = 22222;
        segment.sequence_number = 42;
        segment.acknowledgment_number = 43;
        segment.flags.psh = true;
        segment.flags.ack = true;
        segment.window_size = 4096;
        segment.urgent_pointer = 0;
        segment.payload = toBytes("hello");

        auto result = serializeTcpSegment(segment, ipB(), ipA());
        CHECK(std::holds_alternative<std::vector<std::byte>>(result));
        if (auto* bytes = std::get_if<std::vector<std::byte>>(&result)) {
            CHECK(*bytes == vector3Bytes());
        }
    }

    // known-vector serialize, exact byte comparison against vector 1
    {
        TcpSegment segment;
        segment.source_port = 54321;
        segment.destination_port = 8080;
        segment.sequence_number = 1000;
        segment.acknowledgment_number = 0;
        segment.flags.syn = true;
        segment.window_size = 65535;
        segment.urgent_pointer = 0;

        auto result = serializeTcpSegment(segment, ipA(), ipB());
        CHECK(std::holds_alternative<std::vector<std::byte>>(result));
        if (auto* bytes = std::get_if<std::vector<std::byte>>(&result)) {
            CHECK(*bytes == vector1Bytes());
        }
    }

    // pseudo-header sensitivity: vector 1 bytes, wrong destination IP
    {
        auto wrong_destination = *Ipv4Address::parse("10.0.0.3");
        auto result = parseTcpSegment(vector1Bytes(), ipA(), wrong_destination);
        CHECK(std::holds_alternative<TcpParseError>(result));
        if (auto* err = std::get_if<TcpParseError>(&result)) {
            CHECK(*err == TcpParseError::BadChecksum);
        }
    }

    // round trip
    {
        TcpSegment original;
        original.source_port = 1234;
        original.destination_port = 5678;
        original.sequence_number = 0xdeadbeef;
        original.acknowledgment_number = 0x12345678;
        original.flags.ack = true;
        original.flags.psh = true;
        original.window_size = 4096;
        original.urgent_pointer = 0;
        original.payload = toBytes({1, 2, 3});

        auto serialized = serializeTcpSegment(original, ipA(), ipB());
        CHECK(std::holds_alternative<std::vector<std::byte>>(serialized));
        auto* bytes = std::get_if<std::vector<std::byte>>(&serialized);
        CHECK(bytes != nullptr);
        if (bytes != nullptr) {
            auto result = parseTcpSegment(*bytes, ipA(), ipB());
            CHECK(std::holds_alternative<TcpSegment>(result));
            if (auto* segment = std::get_if<TcpSegment>(&result)) {
                CHECK(segment->source_port == original.source_port);
                CHECK(segment->destination_port == original.destination_port);
                CHECK(segment->sequence_number == original.sequence_number);
                CHECK(segment->acknowledgment_number == original.acknowledgment_number);
                CHECK(segment->flags == original.flags);
                CHECK(segment->window_size == original.window_size);
                CHECK(segment->payload == original.payload);
            }
        }
    }

    // flag encoding/decoding: SYN, ACK, SYN|ACK, FIN, RST, PSH|ACK
    {
        auto roundTripFlags = [](wirestack::TcpFlags flags) {
            TcpSegment segment;
            segment.source_port = 1;
            segment.destination_port = 2;
            segment.sequence_number = 0;
            segment.acknowledgment_number = 0;
            segment.flags = flags;
            segment.window_size = 0;
            segment.urgent_pointer = 0;
            auto serialized = serializeTcpSegment(segment, ipA(), ipB());
            auto* bytes = std::get_if<std::vector<std::byte>>(&serialized);
            auto result = parseTcpSegment(*bytes, ipA(), ipB());
            return std::get<TcpSegment>(result).flags;
        };

        wirestack::TcpFlags syn;
        syn.syn = true;
        CHECK(roundTripFlags(syn) == syn);

        wirestack::TcpFlags ack;
        ack.ack = true;
        CHECK(roundTripFlags(ack) == ack);

        wirestack::TcpFlags syn_ack;
        syn_ack.syn = true;
        syn_ack.ack = true;
        CHECK(roundTripFlags(syn_ack) == syn_ack);

        wirestack::TcpFlags fin;
        fin.fin = true;
        CHECK(roundTripFlags(fin) == fin);

        wirestack::TcpFlags rst;
        rst.rst = true;
        CHECK(roundTripFlags(rst) == rst);

        wirestack::TcpFlags psh_ack;
        psh_ack.psh = true;
        psh_ack.ack = true;
        CHECK(roundTripFlags(psh_ack) == psh_ack);
    }

    // malformed: 0, 1, 19 bytes -> TooShort
    {
        CHECK(std::holds_alternative<TcpParseError>(parseTcpSegment({}, ipA(), ipB())));

        auto one = vector1Bytes();
        one.resize(1);
        CHECK(std::holds_alternative<TcpParseError>(parseTcpSegment(one, ipA(), ipB())));

        auto nineteen = vector1Bytes();
        nineteen.resize(19);
        auto result = parseTcpSegment(nineteen, ipA(), ipB());
        CHECK(std::holds_alternative<TcpParseError>(result));
        if (auto* err = std::get_if<TcpParseError>(&result)) {
            CHECK(*err == TcpParseError::TooShort);
        }
    }

    // malformed: 20 bytes with data offset 4 (< 5) -- rejected before
    // checksum is even examined, so the (now-invalid) checksum field is
    // left untouched.
    {
        auto bytes = vector1Bytes();
        bytes[12] = std::byte{0x40}; // data offset 4
        auto result = parseTcpSegment(bytes, ipA(), ipB());
        CHECK(std::holds_alternative<TcpParseError>(result));
        if (auto* err = std::get_if<TcpParseError>(&result)) {
            CHECK(*err == TcpParseError::InvalidDataOffset);
        }
    }

    // malformed: 20 bytes claiming data offset 6 (header longer than
    // available bytes)
    {
        auto bytes = vector1Bytes();
        bytes[12] = std::byte{0x60}; // data offset 6, but only 20 bytes present
        auto result = parseTcpSegment(bytes, ipA(), ipB());
        CHECK(std::holds_alternative<TcpParseError>(result));
        if (auto* err = std::get_if<TcpParseError>(&result)) {
            CHECK(*err == TcpParseError::InvalidDataOffset);
        }
    }

    // malformed: bad checksum
    {
        auto bytes = vector1Bytes();
        bytes[17] = std::byte{0x37}; // flip a checksum byte
        auto result = parseTcpSegment(bytes, ipA(), ipB());
        CHECK(std::holds_alternative<TcpParseError>(result));
        if (auto* err = std::get_if<TcpParseError>(&result)) {
            CHECK(*err == TcpParseError::BadChecksum);
        }
    }

    // serialization: oversized payload fails explicitly
    {
        TcpSegment segment;
        segment.source_port = 1;
        segment.destination_port = 2;
        segment.sequence_number = 0;
        segment.acknowledgment_number = 0;
        segment.window_size = 0;
        segment.urgent_pointer = 0;
        segment.payload.resize(65536 - 20 + 1);
        auto result = serializeTcpSegment(segment, ipA(), ipB());
        CHECK(std::holds_alternative<TcpSerializeError>(result));
        if (auto* err = std::get_if<TcpSerializeError>(&result)) {
            CHECK(*err == TcpSerializeError::PayloadTooLarge);
        }
    }

    // serialization: unaligned options rejected explicitly (not silently
    // mis-encoded via truncating integer division of the data offset)
    {
        TcpSegment segment;
        segment.source_port = 1;
        segment.destination_port = 2;
        segment.sequence_number = 0;
        segment.acknowledgment_number = 0;
        segment.window_size = 0;
        segment.urgent_pointer = 0;
        segment.options = toBytes({1, 2, 3}); // 3 bytes, not a multiple of 4
        auto result = serializeTcpSegment(segment, ipA(), ipB());
        CHECK(std::holds_alternative<TcpSerializeError>(result));
        if (auto* err = std::get_if<TcpSerializeError>(&result)) {
            CHECK(*err == TcpSerializeError::UnalignedOptions);
        }
    }

    // serialization: options longer than the 40-byte maximum rejected
    {
        TcpSegment segment;
        segment.source_port = 1;
        segment.destination_port = 2;
        segment.sequence_number = 0;
        segment.acknowledgment_number = 0;
        segment.window_size = 0;
        segment.urgent_pointer = 0;
        segment.options.assign(44, std::byte{0}); // aligned, but too long
        auto result = serializeTcpSegment(segment, ipA(), ipB());
        CHECK(std::holds_alternative<TcpSerializeError>(result));
        if (auto* err = std::get_if<TcpSerializeError>(&result)) {
            CHECK(*err == TcpSerializeError::OptionsTooLong);
        }
    }

    // serialization: exactly 40 bytes of aligned options is the maximum
    // supported header and still succeeds
    {
        TcpSegment segment;
        segment.source_port = 1;
        segment.destination_port = 2;
        segment.sequence_number = 0;
        segment.acknowledgment_number = 0;
        segment.window_size = 0;
        segment.urgent_pointer = 0;
        segment.options.assign(40, std::byte{0});
        auto result = serializeTcpSegment(segment, ipA(), ipB());
        CHECK(std::holds_alternative<std::vector<std::byte>>(result));
        if (auto* bytes = std::get_if<std::vector<std::byte>>(&result)) {
            CHECK(bytes->size() == 60);
        }
    }

    // ================= parseTcpOptions =================

    // empty options
    {
        auto result = parseTcpOptions({});
        CHECK(std::holds_alternative<TcpParsedOptions>(result));
        if (auto* parsed = std::get_if<TcpParsedOptions>(&result)) {
            CHECK(!parsed->maximum_segment_size.has_value());
            CHECK(!parsed->window_scale.has_value());
        }
    }

    // EOL only
    {
        auto result = parseTcpOptions(toBytes({0}));
        CHECK(std::holds_alternative<TcpParsedOptions>(result));
    }

    // NOP only / repeated NOP
    {
        CHECK(std::holds_alternative<TcpParsedOptions>(parseTcpOptions(toBytes({1}))));
        CHECK(std::holds_alternative<TcpParsedOptions>(parseTcpOptions(toBytes({1, 1, 1, 1}))));
    }

    // MSS 1460
    {
        auto result = parseTcpOptions(toBytes({2, 4, 0x05, 0xb4}));
        CHECK(std::holds_alternative<TcpParsedOptions>(result));
        if (auto* parsed = std::get_if<TcpParsedOptions>(&result)) {
            CHECK(parsed->maximum_segment_size == 1460);
        }
    }

    // MSS 536
    {
        auto result = parseTcpOptions(toBytes({2, 4, 0x02, 0x18}));
        CHECK(std::holds_alternative<TcpParsedOptions>(result));
        if (auto* parsed = std::get_if<TcpParsedOptions>(&result)) {
            CHECK(parsed->maximum_segment_size == 536);
        }
    }

    // MSS zero: invalid
    {
        auto result = parseTcpOptions(toBytes({2, 4, 0x00, 0x00}));
        CHECK(std::holds_alternative<TcpOptionParseError>(result));
        if (auto* err = std::get_if<TcpOptionParseError>(&result)) {
            CHECK(*err == TcpOptionParseError::InvalidMss);
        }
    }

    // Window Scale 0, 2, 14 -- raw parse only, no clamping here (clamping
    // to 14 happens at negotiation time in tcp_connection.cpp, tested
    // there; the raw parser reports exactly what was on the wire).
    {
        auto ws0 = parseTcpOptions(toBytes({3, 3, 0}));
        CHECK(std::holds_alternative<TcpParsedOptions>(ws0));
        if (auto* parsed = std::get_if<TcpParsedOptions>(&ws0)) CHECK(parsed->window_scale == 0);

        auto ws2 = parseTcpOptions(toBytes({3, 3, 2}));
        CHECK(std::holds_alternative<TcpParsedOptions>(ws2));
        if (auto* parsed = std::get_if<TcpParsedOptions>(&ws2)) CHECK(parsed->window_scale == 2);

        auto ws14 = parseTcpOptions(toBytes({3, 3, 14}));
        CHECK(std::holds_alternative<TcpParsedOptions>(ws14));
        if (auto* parsed = std::get_if<TcpParsedOptions>(&ws14)) CHECK(parsed->window_scale == 14);

        // Window Scale 15: parses successfully as the raw byte 15 --
        // clamping to 14 is a negotiation-time policy, not a parse error.
        auto ws15 = parseTcpOptions(toBytes({3, 3, 15}));
        CHECK(std::holds_alternative<TcpParsedOptions>(ws15));
        if (auto* parsed = std::get_if<TcpParsedOptions>(&ws15)) CHECK(parsed->window_scale == 15);
    }

    // MSS + NOP + Window Scale together
    {
        auto result = parseTcpOptions(toBytes({2, 4, 0x05, 0xb4, 1, 3, 3, 2}));
        CHECK(std::holds_alternative<TcpParsedOptions>(result));
        if (auto* parsed = std::get_if<TcpParsedOptions>(&result)) {
            CHECK(parsed->maximum_segment_size == 1460);
            CHECK(parsed->window_scale == 2);
        }
    }

    // unknown well-formed option: skipped safely, no error, no fields set
    {
        auto result = parseTcpOptions(toBytes({8, 4, 0xaa, 0xbb}));
        CHECK(std::holds_alternative<TcpParsedOptions>(result));
        if (auto* parsed = std::get_if<TcpParsedOptions>(&result)) {
            CHECK(!parsed->maximum_segment_size.has_value());
            CHECK(!parsed->window_scale.has_value());
        }
    }

    // unknown option before a known option
    {
        auto result = parseTcpOptions(toBytes({8, 4, 0xaa, 0xbb, 2, 4, 0x05, 0xb4}));
        CHECK(std::holds_alternative<TcpParsedOptions>(result));
        if (auto* parsed = std::get_if<TcpParsedOptions>(&result)) {
            CHECK(parsed->maximum_segment_size == 1460);
        }
    }

    // EOL followed by padding: parsing stops at EOL, padding ignored safely
    {
        auto result = parseTcpOptions(toBytes({0, 1, 1, 1}));
        CHECK(std::holds_alternative<TcpParsedOptions>(result));
        if (auto* parsed = std::get_if<TcpParsedOptions>(&result)) {
            CHECK(!parsed->maximum_segment_size.has_value());
        }
    }

    // missing length byte
    {
        auto result = parseTcpOptions(toBytes({2}));
        CHECK(std::holds_alternative<TcpOptionParseError>(result));
        if (auto* err = std::get_if<TcpOptionParseError>(&result)) {
            CHECK(*err == TcpOptionParseError::MissingLength);
        }
    }

    // length zero / length one
    {
        auto zero = parseTcpOptions(toBytes({2, 0}));
        CHECK(std::holds_alternative<TcpOptionParseError>(zero));
        if (auto* err = std::get_if<TcpOptionParseError>(&zero)) {
            CHECK(*err == TcpOptionParseError::InvalidLength);
        }

        auto one = parseTcpOptions(toBytes({2, 1}));
        CHECK(std::holds_alternative<TcpOptionParseError>(one));
        if (auto* err = std::get_if<TcpOptionParseError>(&one)) {
            CHECK(*err == TcpOptionParseError::InvalidLength);
        }
    }

    // length beyond remaining bytes
    {
        auto result = parseTcpOptions(toBytes({2, 10, 0, 0}));
        CHECK(std::holds_alternative<TcpOptionParseError>(result));
        if (auto* err = std::get_if<TcpOptionParseError>(&result)) {
            CHECK(*err == TcpOptionParseError::TruncatedOption);
        }
    }

    // truncated MSS (declared length extends past the buffer)
    {
        auto result = parseTcpOptions(toBytes({2, 4, 0x05}));
        CHECK(std::holds_alternative<TcpOptionParseError>(result));
        if (auto* err = std::get_if<TcpOptionParseError>(&result)) {
            CHECK(*err == TcpOptionParseError::TruncatedOption);
        }
    }

    // wrong MSS length (present and in-bounds, but not exactly 4)
    {
        auto result = parseTcpOptions(toBytes({2, 3, 0x05, 0xb4}));
        CHECK(std::holds_alternative<TcpOptionParseError>(result));
        if (auto* err = std::get_if<TcpOptionParseError>(&result)) {
            CHECK(*err == TcpOptionParseError::TruncatedOption);
        }
    }

    // truncated Window Scale
    {
        auto result = parseTcpOptions(toBytes({3, 3}));
        CHECK(std::holds_alternative<TcpOptionParseError>(result));
        if (auto* err = std::get_if<TcpOptionParseError>(&result)) {
            CHECK(*err == TcpOptionParseError::TruncatedOption);
        }
    }

    // wrong Window Scale length
    {
        auto result = parseTcpOptions(toBytes({3, 4, 2, 0}));
        CHECK(std::holds_alternative<TcpOptionParseError>(result));
        if (auto* err = std::get_if<TcpOptionParseError>(&result)) {
            CHECK(*err == TcpOptionParseError::TruncatedOption);
        }
    }

    // duplicate MSS
    {
        auto result = parseTcpOptions(toBytes({2, 4, 0x05, 0xb4, 2, 4, 0x02, 0x18}));
        CHECK(std::holds_alternative<TcpOptionParseError>(result));
        if (auto* err = std::get_if<TcpOptionParseError>(&result)) {
            CHECK(*err == TcpOptionParseError::DuplicateMss);
        }
    }

    // duplicate Window Scale
    {
        auto result = parseTcpOptions(toBytes({3, 3, 2, 3, 3, 4}));
        CHECK(std::holds_alternative<TcpOptionParseError>(result));
        if (auto* err = std::get_if<TcpOptionParseError>(&result)) {
            CHECK(*err == TcpOptionParseError::DuplicateWindowScale);
        }
    }

    // 40-byte option boundary: the maximum possible options region,
    // filled with NOPs, parses without reading out of bounds
    {
        std::vector<std::byte> options(40, std::byte{1}); // all NOP
        auto result = parseTcpOptions(options);
        CHECK(std::holds_alternative<TcpParsedOptions>(result));
    }

    // ================= SACK-Permitted / SACK =================

    // SACK-Permitted alone
    {
        auto result = parseTcpOptions(toBytes({4, 2}));
        CHECK(std::holds_alternative<TcpParsedOptions>(result));
        if (auto* parsed = std::get_if<TcpParsedOptions>(&result)) {
            CHECK(parsed->sack_permitted);
            CHECK(parsed->sack_blocks.empty());
        }
    }

    // SACK-Permitted with MSS
    {
        auto result = parseTcpOptions(toBytes({2, 4, 0x05, 0xb4, 4, 2}));
        CHECK(std::holds_alternative<TcpParsedOptions>(result));
        if (auto* parsed = std::get_if<TcpParsedOptions>(&result)) {
            CHECK(parsed->maximum_segment_size == 1460);
            CHECK(parsed->sack_permitted);
        }
    }

    // SACK-Permitted with Window Scale
    {
        auto result = parseTcpOptions(toBytes({4, 2, 1, 3, 3, 2}));
        CHECK(std::holds_alternative<TcpParsedOptions>(result));
        if (auto* parsed = std::get_if<TcpParsedOptions>(&result)) {
            CHECK(parsed->sack_permitted);
            CHECK(parsed->window_scale == 2);
        }
    }

    // malformed SACK-Permitted length
    {
        auto result = parseTcpOptions(toBytes({4, 3, 0}));
        CHECK(std::holds_alternative<TcpOptionParseError>(result));
        if (auto* err = std::get_if<TcpOptionParseError>(&result)) {
            CHECK(*err == TcpOptionParseError::InvalidSackPermittedLength);
        }
    }

    // missing length byte for kind 4
    {
        auto result = parseTcpOptions(toBytes({4}));
        CHECK(std::holds_alternative<TcpOptionParseError>(result));
        if (auto* err = std::get_if<TcpOptionParseError>(&result)) {
            CHECK(*err == TcpOptionParseError::MissingLength);
        }
    }

    // duplicate SACK-Permitted
    {
        auto result = parseTcpOptions(toBytes({4, 2, 4, 2}));
        CHECK(std::holds_alternative<TcpOptionParseError>(result));
        if (auto* err = std::get_if<TcpOptionParseError>(&result)) {
            CHECK(*err == TcpOptionParseError::DuplicateSackPermitted);
        }
    }

    // one SACK block: left=1001 right=2461
    {
        auto result = parseTcpOptions(toBytes({
            5, 10,                  // kind SACK, length 10 (2 + 8*1)
            0x00, 0x00, 0x03, 0xe9, // left edge 1001
            0x00, 0x00, 0x09, 0x9d, // right edge 2461
        }));
        CHECK(std::holds_alternative<TcpParsedOptions>(result));
        if (auto* parsed = std::get_if<TcpParsedOptions>(&result)) {
            CHECK(parsed->sack_blocks.size() == 1);
            if (parsed->sack_blocks.size() == 1) {
                CHECK(parsed->sack_blocks[0].left_edge == 1001);
                CHECK(parsed->sack_blocks[0].right_edge == 2461);
            }
        }
    }

    // two SACK blocks
    {
        auto result = parseTcpOptions(toBytes({
            5, 18,                  // kind SACK, length 18 (2 + 8*2)
            0x00, 0x00, 0x00, 0x0a, // block 1 left 10
            0x00, 0x00, 0x00, 0x14, // block 1 right 20
            0x00, 0x00, 0x00, 0x1e, // block 2 left 30
            0x00, 0x00, 0x00, 0x28, // block 2 right 40
        }));
        CHECK(std::holds_alternative<TcpParsedOptions>(result));
        if (auto* parsed = std::get_if<TcpParsedOptions>(&result)) {
            CHECK(parsed->sack_blocks.size() == 2);
            if (parsed->sack_blocks.size() == 2) {
                CHECK(parsed->sack_blocks[0].left_edge == 10);
                CHECK(parsed->sack_blocks[0].right_edge == 20);
                CHECK(parsed->sack_blocks[1].left_edge == 30);
                CHECK(parsed->sack_blocks[1].right_edge == 40);
            }
        }
    }

    // four SACK blocks (maximum)
    {
        auto result = parseTcpOptions(toBytes({
            5, 34, // kind SACK, length 34 (2 + 8*4)
            0x00, 0x00, 0x00, 0x0a, 0x00, 0x00, 0x00, 0x14,
            0x00, 0x00, 0x00, 0x1e, 0x00, 0x00, 0x00, 0x28,
            0x00, 0x00, 0x00, 0x32, 0x00, 0x00, 0x00, 0x3c,
            0x00, 0x00, 0x00, 0x46, 0x00, 0x00, 0x00, 0x50,
        }));
        CHECK(std::holds_alternative<TcpParsedOptions>(result));
        if (auto* parsed = std::get_if<TcpParsedOptions>(&result)) {
            CHECK(parsed->sack_blocks.size() == 4);
        }
    }

    // sequence wraparound edges: left=0xfffffff0 right=0x00000010
    {
        auto result = parseTcpOptions(toBytes({
            5, 10, 0xff, 0xff, 0xff, 0xf0, 0x00, 0x00, 0x00, 0x10,
        }));
        CHECK(std::holds_alternative<TcpParsedOptions>(result));
        if (auto* parsed = std::get_if<TcpParsedOptions>(&result)) {
            CHECK(parsed->sack_blocks.size() == 1);
            if (parsed->sack_blocks.size() == 1) {
                CHECK(parsed->sack_blocks[0].left_edge == 0xfffffff0);
                CHECK(parsed->sack_blocks[0].right_edge == 0x00000010);
            }
        }
    }

    // EOL termination after a SACK block
    {
        auto result = parseTcpOptions(toBytes({
            5, 10, 0x00, 0x00, 0x00, 0x0a, 0x00, 0x00, 0x00, 0x14, 0,
        }));
        CHECK(std::holds_alternative<TcpParsedOptions>(result));
        if (auto* parsed = std::get_if<TcpParsedOptions>(&result)) {
            CHECK(parsed->sack_blocks.size() == 1);
        }
    }

    // NOP placement between SACK-Permitted and a SACK block
    {
        auto result = parseTcpOptions(toBytes({
            4, 2, 1, 1, 5, 10, 0x00, 0x00, 0x00, 0x0a, 0x00, 0x00, 0x00, 0x14,
        }));
        CHECK(std::holds_alternative<TcpParsedOptions>(result));
        if (auto* parsed = std::get_if<TcpParsedOptions>(&result)) {
            CHECK(parsed->sack_permitted);
            CHECK(parsed->sack_blocks.size() == 1);
        }
    }

    // unknown option mixed with SACK
    {
        auto result = parseTcpOptions(toBytes({
            8, 4, 0xaa, 0xbb, 5, 10, 0x00, 0x00, 0x00, 0x0a, 0x00, 0x00, 0x00, 0x14,
        }));
        CHECK(std::holds_alternative<TcpParsedOptions>(result));
        if (auto* parsed = std::get_if<TcpParsedOptions>(&result)) {
            CHECK(parsed->sack_blocks.size() == 1);
        }
    }

    // malformed SACK lengths: 2, 9, 11, and truncated 10
    {
        auto len2 = parseTcpOptions(toBytes({5, 2}));
        CHECK(std::holds_alternative<TcpOptionParseError>(len2));
        if (auto* err = std::get_if<TcpOptionParseError>(&len2)) {
            CHECK(*err == TcpOptionParseError::InvalidSackLength);
        }

        auto len9 = parseTcpOptions(
            toBytes({5, 9, 0, 0, 0, 0, 0, 0, 0}));
        CHECK(std::holds_alternative<TcpOptionParseError>(len9));
        if (auto* err = std::get_if<TcpOptionParseError>(&len9)) {
            CHECK(*err == TcpOptionParseError::InvalidSackLength);
        }

        auto len11 = parseTcpOptions(
            toBytes({5, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0}));
        CHECK(std::holds_alternative<TcpOptionParseError>(len11));
        if (auto* err = std::get_if<TcpOptionParseError>(&len11)) {
            CHECK(*err == TcpOptionParseError::InvalidSackLength);
        }

        auto truncated = parseTcpOptions(toBytes({5, 10, 0, 0, 0, 0}));
        CHECK(std::holds_alternative<TcpOptionParseError>(truncated));
        if (auto* err = std::get_if<TcpOptionParseError>(&truncated)) {
            CHECK(*err == TcpOptionParseError::TruncatedOption);
        }
    }

    // too many blocks: length 42 is not a valid SACK length even though
    // it would decode to 5 blocks
    {
        std::vector<std::byte> options(42, std::byte{0});
        options[0] = std::byte{5};
        options[1] = std::byte{42};
        auto result = parseTcpOptions(options);
        CHECK(std::holds_alternative<TcpOptionParseError>(result));
        if (auto* err = std::get_if<TcpOptionParseError>(&result)) {
            CHECK(*err == TcpOptionParseError::InvalidSackLength);
        }
    }

    // duplicate SACK
    {
        auto result = parseTcpOptions(toBytes({
            5, 10, 0x00, 0x00, 0x00, 0x0a, 0x00, 0x00, 0x00, 0x14,
            5, 10, 0x00, 0x00, 0x00, 0x1e, 0x00, 0x00, 0x00, 0x28,
        }));
        CHECK(std::holds_alternative<TcpOptionParseError>(result));
        if (auto* err = std::get_if<TcpOptionParseError>(&result)) {
            CHECK(*err == TcpOptionParseError::DuplicateSack);
        }
    }

    // maximum 40-byte option area: MSS + SACK-Permitted + NOP + Window
    // Scale + a 3-block SACK + EOL padding, exactly 40 bytes (10 + 26 + 4)
    {
        std::vector<std::byte> options = toBytes({
            2, 4, 0x05, 0xb4, // MSS
            4, 2,             // SACK-Permitted
            1, 3, 3, 2,       // NOP + Window Scale
        });
        std::vector<std::byte> sack = toBytes({
            5, 26, // SACK, 3 blocks
            0x00, 0x00, 0x00, 0x0a, 0x00, 0x00, 0x00, 0x14,
            0x00, 0x00, 0x00, 0x1e, 0x00, 0x00, 0x00, 0x28,
            0x00, 0x00, 0x00, 0x32, 0x00, 0x00, 0x00, 0x3c,
        });
        options.insert(options.end(), sack.begin(), sack.end());
        options.insert(options.end(), 4, std::byte{0}); // EOL + padding
        CHECK(options.size() == 40);
        auto result = parseTcpOptions(options);
        CHECK(std::holds_alternative<TcpParsedOptions>(result));
        if (auto* parsed = std::get_if<TcpParsedOptions>(&result)) {
            CHECK(parsed->maximum_segment_size == 1460);
            CHECK(parsed->sack_permitted);
            CHECK(parsed->window_scale == 2);
            CHECK(parsed->sack_blocks.size() == 3);
        }
    }

    return wirestack::test::failureCount() == 0 ? 0 : 1;
}
