// Checksum vectors in this file were computed independently with a
// throwaway Python script (RFC 1071 algorithm over the IPv4 pseudo-header
// + TCP segment) and hardcoded here -- never generated by calling
// Wirestack's own tcp.cpp code.

#include "wirestack/tcp.hpp"

#include "test_util.hpp"

using wirestack::Ipv4Address;
using wirestack::parseTcpSegment;
using wirestack::serializeTcpSegment;
using wirestack::TcpParseError;
using wirestack::TcpSegment;
using wirestack::TcpSerializeError;

namespace {

std::vector<std::byte> toBytes(std::initializer_list<std::uint8_t> values) {
    std::vector<std::byte> out;
    out.reserve(values.size());
    for (auto v : values) {
        out.push_back(static_cast<std::byte>(v));
    }
    return out;
}

std::vector<std::byte> toBytes(std::string_view text) {
    std::vector<std::byte> out;
    out.reserve(text.size());
    for (char c : text) {
        out.push_back(static_cast<std::byte>(static_cast<unsigned char>(c)));
    }
    return out;
}

Ipv4Address ipA() {
    return *Ipv4Address::parse("10.0.0.1");
}
Ipv4Address ipB() {
    return *Ipv4Address::parse("10.0.0.2");
}

// Vector 1: SYN, no options, no payload. src=10.0.0.1 dst=10.0.0.2,
// srcport=54321 dstport=8080 seq=1000 ack=0 flags=SYN window=65535.
// Checksum 0xa436, independently computed.
std::vector<std::byte> vector1Bytes() {
    return toBytes({
        0xd4, 0x31,             // source port 54321
        0x1f, 0x90,             // destination port 8080
        0x00, 0x00, 0x03, 0xe8, // sequence number 1000
        0x00, 0x00, 0x00, 0x00, // acknowledgment number 0
        0x50, 0x02,             // data offset 5, flags SYN
        0xff, 0xff,             // window 65535
        0xa4, 0x36,             // checksum
        0x00, 0x00,             // urgent pointer
    });
}

// Vector 2: SYN|ACK with a 4-byte options area (data offset 6, 24-byte
// header). src=10.0.0.2 dst=10.0.0.1 srcport=8080 dstport=54321 seq=5000
// ack=1001 flags=SYN|ACK window=14600 options={02 04 05 b4}.
// Checksum 0x3fd9, independently computed.
std::vector<std::byte> vector2Bytes() {
    return toBytes({
        0x1f, 0x90,             // source port 8080
        0xd4, 0x31,             // destination port 54321
        0x00, 0x00, 0x13, 0x88, // sequence number 5000
        0x00, 0x00, 0x03, 0xe9, // acknowledgment number 1001
        0x60, 0x12,             // data offset 6, flags SYN|ACK
        0x39, 0x08,             // window 14600
        0x3f, 0xd9,             // checksum
        0x00, 0x00,             // urgent pointer
        0x02, 0x04, 0x05, 0xb4, // options (opaque to Wirestack)
    });
}

// Vector 3: PSH|ACK with a 5-byte payload (odd total length: 25 bytes).
// src=10.0.0.2 dst=10.0.0.1 srcport=11111 dstport=22222 seq=42 ack=43
// flags=PSH|ACK window=4096 payload="hello". Checksum 0xc568,
// independently computed.
std::vector<std::byte> vector3Bytes() {
    return toBytes({
        0x2b, 0x67,             // source port 11111
        0x56, 0xce,             // destination port 22222
        0x00, 0x00, 0x00, 0x2a, // sequence number 42
        0x00, 0x00, 0x00, 0x2b, // acknowledgment number 43
        0x50, 0x18,             // data offset 5, flags PSH|ACK
        0x10, 0x00,             // window 4096
        0xc5, 0x68,             // checksum
        0x00, 0x00,             // urgent pointer
        0x68, 0x65, 0x6c, 0x6c, 0x6f, // "hello"
    });
}

} // namespace

int main() {
    // known-vector parse: base 20-byte SYN
    {
        auto result = parseTcpSegment(vector1Bytes(), ipA(), ipB());
        CHECK(std::holds_alternative<TcpSegment>(result));
        if (auto* segment = std::get_if<TcpSegment>(&result)) {
            CHECK(segment->source_port == 54321);
            CHECK(segment->destination_port == 8080);
            CHECK(segment->sequence_number == 1000);
            CHECK(segment->acknowledgment_number == 0);
            CHECK(segment->flags.syn);
            CHECK(!segment->flags.ack);
            CHECK(segment->window_size == 65535);
            CHECK(segment->options.empty());
            CHECK(segment->payload.empty());
        }
    }

    // known-vector parse: options present, data offset 6 -- proves Data
    // Offset is honored, not assumed to be 20 bytes.
    {
        auto result = parseTcpSegment(vector2Bytes(), ipB(), ipA());
        CHECK(std::holds_alternative<TcpSegment>(result));
        if (auto* segment = std::get_if<TcpSegment>(&result)) {
            CHECK(segment->source_port == 8080);
            CHECK(segment->destination_port == 54321);
            CHECK(segment->sequence_number == 5000);
            CHECK(segment->acknowledgment_number == 1001);
            CHECK(segment->flags.syn);
            CHECK(segment->flags.ack);
            CHECK(segment->options == toBytes({0x02, 0x04, 0x05, 0xb4}));
            CHECK(segment->payload.empty());
        }
    }

    // known-vector parse: odd total length, payload slicing with a
    // 5-byte payload -- second independent checksum vector.
    {
        auto result = parseTcpSegment(vector3Bytes(), ipB(), ipA());
        CHECK(std::holds_alternative<TcpSegment>(result));
        if (auto* segment = std::get_if<TcpSegment>(&result)) {
            CHECK(segment->flags.psh);
            CHECK(segment->flags.ack);
            CHECK(!segment->flags.syn);
            CHECK(segment->payload == toBytes("hello"));
        }
    }

    // known-vector serialize, exact byte comparison against vector 3 --
    // proves serialization independently, not just parsing, for this
    // odd-length vector.
    {
        TcpSegment segment;
        segment.source_port = 11111;
        segment.destination_port = 22222;
        segment.sequence_number = 42;
        segment.acknowledgment_number = 43;
        segment.flags.psh = true;
        segment.flags.ack = true;
        segment.window_size = 4096;
        segment.urgent_pointer = 0;
        segment.payload = toBytes("hello");

        auto result = serializeTcpSegment(segment, ipB(), ipA());
        CHECK(std::holds_alternative<std::vector<std::byte>>(result));
        if (auto* bytes = std::get_if<std::vector<std::byte>>(&result)) {
            CHECK(*bytes == vector3Bytes());
        }
    }

    // known-vector serialize, exact byte comparison against vector 1
    {
        TcpSegment segment;
        segment.source_port = 54321;
        segment.destination_port = 8080;
        segment.sequence_number = 1000;
        segment.acknowledgment_number = 0;
        segment.flags.syn = true;
        segment.window_size = 65535;
        segment.urgent_pointer = 0;

        auto result = serializeTcpSegment(segment, ipA(), ipB());
        CHECK(std::holds_alternative<std::vector<std::byte>>(result));
        if (auto* bytes = std::get_if<std::vector<std::byte>>(&result)) {
            CHECK(*bytes == vector1Bytes());
        }
    }

    // pseudo-header sensitivity: vector 1 bytes, wrong destination IP
    {
        auto wrong_destination = *Ipv4Address::parse("10.0.0.3");
        auto result = parseTcpSegment(vector1Bytes(), ipA(), wrong_destination);
        CHECK(std::holds_alternative<TcpParseError>(result));
        if (auto* err = std::get_if<TcpParseError>(&result)) {
            CHECK(*err == TcpParseError::BadChecksum);
        }
    }

    // round trip
    {
        TcpSegment original;
        original.source_port = 1234;
        original.destination_port = 5678;
        original.sequence_number = 0xdeadbeef;
        original.acknowledgment_number = 0x12345678;
        original.flags.ack = true;
        original.flags.psh = true;
        original.window_size = 4096;
        original.urgent_pointer = 0;
        original.payload = toBytes({1, 2, 3});

        auto serialized = serializeTcpSegment(original, ipA(), ipB());
        CHECK(std::holds_alternative<std::vector<std::byte>>(serialized));
        auto* bytes = std::get_if<std::vector<std::byte>>(&serialized);
        CHECK(bytes != nullptr);
        if (bytes != nullptr) {
            auto result = parseTcpSegment(*bytes, ipA(), ipB());
            CHECK(std::holds_alternative<TcpSegment>(result));
            if (auto* segment = std::get_if<TcpSegment>(&result)) {
                CHECK(segment->source_port == original.source_port);
                CHECK(segment->destination_port == original.destination_port);
                CHECK(segment->sequence_number == original.sequence_number);
                CHECK(segment->acknowledgment_number == original.acknowledgment_number);
                CHECK(segment->flags == original.flags);
                CHECK(segment->window_size == original.window_size);
                CHECK(segment->payload == original.payload);
            }
        }
    }

    // flag encoding/decoding: SYN, ACK, SYN|ACK, FIN, RST, PSH|ACK
    {
        auto roundTripFlags = [](wirestack::TcpFlags flags) {
            TcpSegment segment;
            segment.source_port = 1;
            segment.destination_port = 2;
            segment.sequence_number = 0;
            segment.acknowledgment_number = 0;
            segment.flags = flags;
            segment.window_size = 0;
            segment.urgent_pointer = 0;
            auto serialized = serializeTcpSegment(segment, ipA(), ipB());
            auto* bytes = std::get_if<std::vector<std::byte>>(&serialized);
            auto result = parseTcpSegment(*bytes, ipA(), ipB());
            return std::get<TcpSegment>(result).flags;
        };

        wirestack::TcpFlags syn;
        syn.syn = true;
        CHECK(roundTripFlags(syn) == syn);

        wirestack::TcpFlags ack;
        ack.ack = true;
        CHECK(roundTripFlags(ack) == ack);

        wirestack::TcpFlags syn_ack;
        syn_ack.syn = true;
        syn_ack.ack = true;
        CHECK(roundTripFlags(syn_ack) == syn_ack);

        wirestack::TcpFlags fin;
        fin.fin = true;
        CHECK(roundTripFlags(fin) == fin);

        wirestack::TcpFlags rst;
        rst.rst = true;
        CHECK(roundTripFlags(rst) == rst);

        wirestack::TcpFlags psh_ack;
        psh_ack.psh = true;
        psh_ack.ack = true;
        CHECK(roundTripFlags(psh_ack) == psh_ack);
    }

    // malformed: 0, 1, 19 bytes -> TooShort
    {
        CHECK(std::holds_alternative<TcpParseError>(parseTcpSegment({}, ipA(), ipB())));

        auto one = vector1Bytes();
        one.resize(1);
        CHECK(std::holds_alternative<TcpParseError>(parseTcpSegment(one, ipA(), ipB())));

        auto nineteen = vector1Bytes();
        nineteen.resize(19);
        auto result = parseTcpSegment(nineteen, ipA(), ipB());
        CHECK(std::holds_alternative<TcpParseError>(result));
        if (auto* err = std::get_if<TcpParseError>(&result)) {
            CHECK(*err == TcpParseError::TooShort);
        }
    }

    // malformed: 20 bytes with data offset 4 (< 5) -- rejected before
    // checksum is even examined, so the (now-invalid) checksum field is
    // left untouched.
    {
        auto bytes = vector1Bytes();
        bytes[12] = std::byte{0x40}; // data offset 4
        auto result = parseTcpSegment(bytes, ipA(), ipB());
        CHECK(std::holds_alternative<TcpParseError>(result));
        if (auto* err = std::get_if<TcpParseError>(&result)) {
            CHECK(*err == TcpParseError::InvalidDataOffset);
        }
    }

    // malformed: 20 bytes claiming data offset 6 (header longer than
    // available bytes)
    {
        auto bytes = vector1Bytes();
        bytes[12] = std::byte{0x60}; // data offset 6, but only 20 bytes present
        auto result = parseTcpSegment(bytes, ipA(), ipB());
        CHECK(std::holds_alternative<TcpParseError>(result));
        if (auto* err = std::get_if<TcpParseError>(&result)) {
            CHECK(*err == TcpParseError::InvalidDataOffset);
        }
    }

    // malformed: bad checksum
    {
        auto bytes = vector1Bytes();
        bytes[17] = std::byte{0x37}; // flip a checksum byte
        auto result = parseTcpSegment(bytes, ipA(), ipB());
        CHECK(std::holds_alternative<TcpParseError>(result));
        if (auto* err = std::get_if<TcpParseError>(&result)) {
            CHECK(*err == TcpParseError::BadChecksum);
        }
    }

    // serialization: oversized payload fails explicitly
    {
        TcpSegment segment;
        segment.source_port = 1;
        segment.destination_port = 2;
        segment.sequence_number = 0;
        segment.acknowledgment_number = 0;
        segment.window_size = 0;
        segment.urgent_pointer = 0;
        segment.payload.resize(65536 - 20 + 1);
        auto result = serializeTcpSegment(segment, ipA(), ipB());
        CHECK(std::holds_alternative<TcpSerializeError>(result));
        if (auto* err = std::get_if<TcpSerializeError>(&result)) {
            CHECK(*err == TcpSerializeError::PayloadTooLarge);
        }
    }

    // serialization: unaligned options rejected explicitly (not silently
    // mis-encoded via truncating integer division of the data offset)
    {
        TcpSegment segment;
        segment.source_port = 1;
        segment.destination_port = 2;
        segment.sequence_number = 0;
        segment.acknowledgment_number = 0;
        segment.window_size = 0;
        segment.urgent_pointer = 0;
        segment.options = toBytes({1, 2, 3}); // 3 bytes, not a multiple of 4
        auto result = serializeTcpSegment(segment, ipA(), ipB());
        CHECK(std::holds_alternative<TcpSerializeError>(result));
        if (auto* err = std::get_if<TcpSerializeError>(&result)) {
            CHECK(*err == TcpSerializeError::UnalignedOptions);
        }
    }

    // serialization: options longer than the 40-byte maximum rejected
    {
        TcpSegment segment;
        segment.source_port = 1;
        segment.destination_port = 2;
        segment.sequence_number = 0;
        segment.acknowledgment_number = 0;
        segment.window_size = 0;
        segment.urgent_pointer = 0;
        segment.options.assign(44, std::byte{0}); // aligned, but too long
        auto result = serializeTcpSegment(segment, ipA(), ipB());
        CHECK(std::holds_alternative<TcpSerializeError>(result));
        if (auto* err = std::get_if<TcpSerializeError>(&result)) {
            CHECK(*err == TcpSerializeError::OptionsTooLong);
        }
    }

    // serialization: exactly 40 bytes of aligned options is the maximum
    // supported header and still succeeds
    {
        TcpSegment segment;
        segment.source_port = 1;
        segment.destination_port = 2;
        segment.sequence_number = 0;
        segment.acknowledgment_number = 0;
        segment.window_size = 0;
        segment.urgent_pointer = 0;
        segment.options.assign(40, std::byte{0});
        auto result = serializeTcpSegment(segment, ipA(), ipB());
        CHECK(std::holds_alternative<std::vector<std::byte>>(result));
        if (auto* bytes = std::get_if<std::vector<std::byte>>(&result)) {
            CHECK(bytes->size() == 60);
        }
    }

    return wirestack::test::failureCount() == 0 ? 0 : 1;
}
